services:
  - type: web
    name: WhatsCrap
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: WhatsCrapDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: WhatsCrapDB
    plan: free
